# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AeEzVt2-q9w8oDfmmLXxdlkJ8Wm9MPv
"""

from flask import Flask, render_template, request
import random

app = Flask(__name__)   # Flask App 생성하기


# 점심 메뉴 추천 함수

def select_menu():
    menu_list = [
        '짜장면', '짬뽕', '탕수육', '볶음밥', '자장밥', '삼겹살', '치킨', '피자', '초밥'
        , '가츠동', '제육볶음', '생선구이', '쌀국수', '순대국', '김치찌개', '돈까스', '순두부찌개'
        , '부대찌개', '햄버거', '칼국수', '분식', '텐동', '곰탕', '갈비탕', '찜닭', '라멘', '샐러드', '샌드위치']

    return random.choice(menu_list)  # 메뉴 리스트에서 랜덤으로 하나 뽑기


# 웹 페이지의 라우팅 설정
@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        menu = select_menu()
        return render_template('index.html', menu=menu)  # menu라는 변수에 저장된 내용을 index.html에 반영
    return render_template('index.html')


# 앱 실행
if __name__ == '__main__':
    app.run()

#앱실행
export FLASK_APP=__init__.py
flask run

"""# 비고

Flask는 웹 프레임워크로, 간단한 앱부터 복잡한 앱까지 다양한 웹 애플리케이션을 만들 수 있습니다. HTML, CSS, Javascript 등에 대한 이해도 어느 정도 있어야 괜찮은 웹사이트를 만들 수 있지만, 보통 무료로 제공하는 템플릿을 가져다가 사용하면 뚝딱 만들 수 있습니다. Flask 앱의 최소 구조는 다음과 같습니다:
app/
 ㄴ static/  # css, js, 이미지 등을 저장하는 디렉토리입니다.
    ㄴ style.css  
 ㄴ templates/ # HTML 파일을 저장하는 디렉터리입니다.
    ㄴ index.html
ㄴ __init__.py # Flask 앱을 생성하고 실행할 때 사용하는 파일입니다
"""

# 플라스크 설치
"pip install flask"