# -*- coding: utf-8 -*-
"""JP__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYutgDf7hSkXr3PNo3_ExbsmmtmWSnm7
"""

from flask import Flask, render_template, request
import random

app = Flask(__name__)   # Flask App 生成

def select_menu():
    menu_list = [
        'ラーメン', 'ハンバーガー', '中華', '韓食', 'コンビニ', '無し', 'うどん', 'そば', '寿司'
        , 'カツ丼', '天丼', '豚カツ', 'パン']

    return random.choice(menu_list)


# WEBページのRouting設定
@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        menu = select_menu()
        return render_template('index.html', menu=menu)
    return render_template('index.html')


# 実行
if __name__ == '__main__':
    app.run()

#APP実行
export FLASK_APP=__init__.py
flask run

"""# Text

Flaskはウェブフレームワークであり、シンプルなアプリから複雑なアプリまでさまざまなウェブアプリケーションを作成することができます。HTML、CSS、JavaScriptなどの理解があると、良質なウェブサイトを作成することができますが、通常は無料で提供されているテンプレートを使用することで簡単に作成することができます。Flaskアプリの最小構造は次のようになります
app/
 ㄴ static/ # CSS、JS、画像などを保存するディレクトリです。
    ㄴ style.css
 ㄴ templates/ # HTMLファイルを保存するディレクトリです。
    ㄴ index.html
 ㄴ init.py # Flaskアプリを作成して実行するために使用するファイルです。
"""

# install flask lib
#pip install flask